### ISSUE TITLE
N'utiliser qu'une valeur seuil pour le filtre médian

### ISSUE THREAD

**Issue by MiboraMinima** [MiboraMinima/st_dbscan_sa#1]
Comme indiquer par Colin, il est préférable d'utiliser une valeur unique pour le filtre médian. On préserve ainsi la variabilité de l'échantillon afin que le modèle soit plus flexible au final. Une figure (y=dmed, x=distance) et des refs à la littérature sont attendues pour motiver le choix du seuil.

Il faut changer cette partie du code dans le fichier `scripts/data_prep.r`:

```r
# Find threshold for each track. Using percentile. !!Arbitrary 95e pct!!
track_list <- unique(train_clean$id_trace)

clean_track <- list()
th_list <- list()
for (i in seq_along(track_list)) {
  lab_id <- track_list[i]

  # Compute threshold
  c_track <- train_clean[train_clean$id_trace == lab_id, ]
  q95 <- quantile(c_track$dmed, probs = c(.95))

  # Store data
  clean_track[[lab_id]] <- c_track[c_track$dmed < q95, ]
  th_list[[lab_id]] <- q95
}

# Stats desc on thresholds -> HIGH variability (very interesting for a critical
# analysis)
summarytools::descr(unlist(th_list))

# Merge all df
df_clean <- reshape::merge_all(clean_track)

# Show how many pings have been removed
n_rem <- nrow(train_clean) - nrow(df_clean)
pct_rem <- (n_rem / nrow(df_clean)) * 100
sprintf(
  "%s (%s %% of total) pings removed using 95e pct for each track",
  n_rem, round(pct_rem)
)
```

**Comment by angelinepi** [comment]
J'ajoute en commentaire qu'il nous avait suggéré de regarder la distance des points par rapport à leur médiane (voir la forme de la courbe, trouver une rupture) : en dessinant des graphiques des traces et des médianes
Et voir dans la bibliographie...

S'il y a un "usage", une tendance.
Peut-être que la rupture se fait souvent au même moment... ou bien que ça suit une loi normale par exemple... (je sais pas x) )

**Comment by angelinepi** [comment]
J'avoue que j'ai pas regardé la biblio pour ça...
j'ai rajouté les graphiques des traces & médianes, outliers
ainsi que des histo de distributions distances médianes
+ choix d'un seuil fixe pour toutes les traces
