### ISSUE TITLE
Définition des paramètres

### ISSUE THREAD

**Issue by MiboraMinima** [MiboraMinima/st_dbscan_sa#3]
Il faut revoir les paramètres du stdbscan. Actuellement : 

```r
df_store <- expand.grid(
  minpts = seq(5, 30, 5),
  eps    = seq(1, 5, 0.75),
  eps2   = seq(30, 180, 30),
  id     = unique(df_clean$id)
)
```

On s'est dit que 5 mètres pour `eps` c'était ambitieux eu égard à la précision des GPS. Il y a une forte relation entre `minpts` et `eps`, il est important de la prendre en compte. `eps2` doit être considéré comme un paramètre de discrétisation. 

Actuellement, on est à 6 valeurs par paramètres, on peut bourrer dans la mesure où la parallélisation des CPUs permet de réduire considérablement le temps de calcul.

**Comment by angelinepi** [comment]
J'avais noté aussi qu'il proposait qu'on tester d'autres précisions, notamment qu'on affiner tous les mètres et toutes les secondes
Et qu'on représente le tout sous un graphique heatmap avec y = eps, et x = minpts

**Comment by MiboraMinima** [comment]
> qu'on représente le tout sous un graphique heatmap avec y = eps, et x = minpts

Ça on peut le faire dans #4 je pense

> qu'on vérifie le paramètre par defaut de st_bdscan, temps car ce n'est peut-être pas le même format que nos traces

J'en parle dans la discussion #5

**Comment by MiboraMinima** [comment]
Close in #13
